name: Publish to npm

on:
  push:
    tags:
      - 'v*' # This will trigger the workflow when a tag starting with 'v' is pushed

# Add explicit permissions for the workflow
permissions:
  contents: write # This is needed for creating releases
  packages: write # This is needed for publishing packages

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build plugin
        run: pnpm --filter vue-proximity-prefetch run build

      - name: Run tests
        run: pnpm --filter vue-proximity-prefetch test || true # Continue even if tests fail

      - name: Publish to npm
        working-directory: ./packages/vue-proximity-prefetch
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: |
            packages/vue-proximity-prefetch/dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}